# Generated by Django 4.2.5 on 2023-09-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20230919_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmodel',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
